name: Go

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.15.7

    - name: Install
      run: go get -u github.com/mattn/go-bindata/...
    - name: Install
      run: go get -u github.com/goadesign/goa/...
    - name: Install
      run: go get -u github.com/golang/dep/cmd/dep
    - name: Install
      run: GO111MODULE=on go get golang.org/x/tools/gopls@v0.6.6
    - name: Install
      run: go get -u github.com/derekparker/delve/cmd/dlv
    - name: Install
      run: apt-get update
    - name: Install
      run: apt-get -y install graphviz
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
